spring:
  jpa:
    database: HSQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    url:
    jdbcUrl: jdbc:hsqldb:hsql://localhost/autenticacao
    username: sa
    password:
    driverClassName: org.hsqldb.jdbcDriver

  redis:
    host: 127.0.0.1
    port: 6379
#    host: 192.168.50.1
#    port: 6381

  session:
    redis:
      flush-mode: immediate
      cleanup-cron: 0 * * * * *

app-config:
  upload-async: false
  url-origin-cors: http://localhost

flyway:
  enabled: false
