spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    url: jdbc:oracle:thin:@//192.168.50.2:1521/dev
    username: AUTENTICACAO_TEST
    password: py12nrk7
    #url: jdbc:oracle:thin:@//localhost:49161/xe
    #username: system
    #password: oracle

    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 2

flyway:
  enabled: false
