server:
  port: 8096
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

spring:
  application:
      name: autenticacao-api
  redis:
#    host: 127.0.0.1
    host: 192.168.50.1
    port: 6379

    pool:
      max-active: 120
      max-idle: 40

  resources:
    chain:
      cache: false
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: br.com.xbrain.autenticacao.config.database.CustomOracle10gDialect
        hbm2ddl:
          import_files:
            database/estrutura.sql,
            database/organizacional.sql,
            database/permissoes.sql,
            database/cidades.sql,
            database/motivo-inativacao.sql,
            database/feriados.sql
        format_sql: false

  datasource:
    url: jdbc:oracle:thin:@//192.168.50.2:1521/dev
    username: AUTENTICACAO
    password: 4ut3nt1c4c40
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximumPoolSize: 2
      connectionTimeout: 10000

  rabbitmq:
    host: 192.168.50.1
#    host: localhost
    port: 5671
    username: xbrain
    password: xbrain

  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    encoding: UTF-8

app-config:
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-10-11T00:00:00.000
    email-usuario-viabilidade: INTEGRACAOMOTIVA@XBRAIN.COM.BR,INTEGRACAODDCOM@XBRAIN.COM.BR,INTEGRACAOCREDITCASH@XBRAIN.COM.BR
  upload-async: true
  nome: Colaboradores
  url: http://localhost:3100
  url-estatico: https://estatico-hom.conexaoclarobrasil.com.br
  url-estatico-upload: ${app-config.url-estatico}/desenvolvimento/autenticacao
  url-origin-cors: http://localhost
  estatico-dir: /opt/servidor_estatico/conexao_claro_brasil
  upload-dir: ${app-config.estatico-dir}/desenvolvimento/autenticacao

  usuario-foto:
    dir: ${app-config.upload-dir}/usuario/foto
    url: ${app-config.url-estatico-upload}/usuario/foto

  email:
    enviar: true
    empresa-alias: XBRAIN
    emails: viola@xbrain.com.br,jose@xbrain.com.br
    emails-solicitacao-ramal: jose@xbrain.com.br

  multiplo-login:
    emails: colaborador@claro.com.br

  topic:
    autenticacao: autenticacao.topic
    mailing: mailing.topic
    feeder: feeder.topic

  queue:
    usuario-cadastro: usuario-cadastro.queue
    usuario-cidade: usuario-cidade.queue
    usuario-cadastro-success: usuario-cadastro-success.queue
    usuario-cadastro-socio-principal-success: usuario-cadastro-socio-principal-success.queue
    usuario-cadastro-loja-futuro-success: usuario-cadastro-loja-futuro-success.queue
    usuario-colaborador-success: usuario-colaborador-success.queue
    usuario-cadastro-failure: usuario-cadastro-failure.queue
    usuario-atualizacao: usuario-atualizacao.queue
    usuario-atualizacao-lojafuturo: usuario-atualizacao-lojafuturo.queue
    usuario-atualizacao-failure: usuario-atualizacao-failure.queue
    usuario-aa-atualizacao: usuario-aa-atualizacao.queue
    usuario-aa-atualizacao-failure: usuario-aa-atualizacao-failure.queue
    usuario-recuperacao: usuario-recuperacao.queue
    usuario-recuperacao-failure: usuario-recuperacao-failure.queue
    usuario-alterar-email: usuario-alterar-email.queue
    usuario-alterar-cargo: usuario-alterar-cargo.queue
    usuario-ativar: usuario-ativar.queue
    usuario-inativar: usuario-inativar.queue
    usuario-alterar-senha: usuario-alterar-senha.queue
    usuario-alterar-situacao: usuario-alterar-situacao.queue
    usuario-logout: usuario-logout.queue
    usuario-logout-failure: usuario-logout-failure.queue
    atualizar-usuario-pol: atualizar-usuario-pol.queue
    inativar-usuario-equipe-venda: inativar-usuario-equipe-venda.queue
    inativar-colaborador-pol: inativar-colaborador-pol.queue
    distribuir-tabulacoes: distribuir-tabulacoes.queue
    usuario-ultimo-acesso-pol: usuario-ultimo-acesso-pol.queue
    atualizar-permissao-feeder: permissao-feeder-aa-atualizacao.queue
    atualizar-permissao-feeder-failure: permissao-feeder-aa-atualizacao-failure.queue
    usuario-remanejar-pol: usuario-remanejar-pol.queue
    usuario-remanejado-aut: usuario-remanejado-aut.queue
    usuario-remanejado-aut-failure: usuario-remanejado-aut-failure.queue
    cadastro-usuario-feeder: cadastro-usuario-feeder.queue
    cadastro-usuario-feeder-failure: cadastro-usuario-feeder-failure.queue
    sucesso-cadastro-usuario-feeder: sucesso-cadastro-usuario-feeder.queue
    sucesso-cadastro-usuario-feeder-failure: sucesso-cadastro-usuario-feeder-failure.queue
    alterar-situacao-usuario-feeder: alterar-situacao-usuario-feeder.queue
    alterar-situacao-usuario-feeder-failure: alterar-situacao-usuario-feeder-failure.queue
    usuario-inativacao-por-aa: usuario-inativacao-por-aa.queue
    limpar-cpf-e-alterar-email-feeder: limpar-cpf-e-alterar-email-feeder.queue
    limpar-cpf-e-alterar-email-feeder-failure: limpar-cpf-e-alterar-email-feeder-failure.queue
    permissao-agente-autorizado-equipe-tecnica: permissao-agente-autorizado-equipe-tecnica.queue
    permissao-agente-autorizado-equipe-tecnica-failure: permissao-agente-autorizado-equipe-tecnica-failure.queue
    atualizar-permissao-tecnico-indicador: atualizar-permissao-tecnico-indicador.queue
    atualizar-permissao-tecnico-indicador-failure: atualizar-permissao-tecnico-indicador-failure.queue
    organizacao-empresa-atualizacao-nome: organizacao-empresa-atualizacao-nome.queue
    organizacao-empresa-atualizacao-nome-failure: organizacao-empresa-atualizacao-nome-failure.queue

  oauth-clients:
    autenticacao-api:
      client: autenticacao-api
      secret: 4ut3nt1c4c404p1
    backoffice-api:
      client: backoffice-api
      secret: b4ck0ff1c34p1
    front-apps:
      client: xbrain-app-client
      secret: xbrain
    parceiros-online-api:
      client: parceiros-online-api
      secret: p4rc31r0s$p1
    integracao-vendas-api:
      client: integracao-vendas-api
      secret: 1nt3gr4c40v3nd4s4p1
    integracao-brscan-api:
      client: integracao-brscan-api
      secret: 1nt3gr4c40brsc4n
    vendas-api:
      client: vendas-api
      secret: v3nd4s4p1
    mailing-api:
      client: mailing-api
      secret: m41l1ng4p1
    mailing-discadora-api:
      client: mailing-discadora-api
      secret: m41l1ng4d1sc4d0r44p1
    mailing-importacao-api:
      client: mailing-importacao-api
      secret: m41l1ng1mp0rt4c404p1
    call-api:
      client: call-api
      secret: c4ll4p1
    varejo-api:
      client: varejo-api
      secret: v4r3j04p1
    equipe-venda-api:
      client: equipe-venda-api
      secret: 3qu1p3V3nD4xbr41n
    dashboard-api:
      client: dashboard-api
      secret: d4shb04rd
    discadora-eccp-api:
      client: discadora-eccp-api
      secret: d1sc4d0r43ccp4p1
    contato-crn-api:
      client: contato-crn-api
      secret: c0nt4t0crn4p1
    chamado-api:
      client: chamado-api
      secret: ch4m4d04p1
    funil-prospeccao-api:
      client: funil-prospeccao-api
      secret: fun1lpr0sp3cc40
    discadora-api:
      client: discadora-api
      secret: d1sc4d0r4
    asterisk-ura-api:
      client: asterisk-ura-api
      secret: 4st3r1skur44p1
    gerador-lead-api:
      client: gerador-lead-api
      secret: g3r4d0rl34d4p1
    indicacao-api:
      client: indicacao-api
      secret: 1nd1c4c40
    agente-autorizado-api:
      client: agente-autorizado-api
      secret: 4g3nt34ut0r1z4d0
    colaborador-vendas-api:
      client: colaborador-vendas-api
      secret: c0l4b0r4d0rv3nd4s
    click-to-call-api:
      client: click-to-call-api
      secret: cl1ckt0c4ll4p1
    chatbot-api:
      client: chatbot-api
      secret: chb78%Pz
    solicitacao-pap-api:
      client: solicitacao-pap-api
      secret: s0l1c1t4c40p4p4p1
    claro-indico-api:
      client: claro-indico-api
      secret: cl4r0_1nd1c0_4p1
    lei-nao-perturbe-api:
      client: lei-nao-perturbe-api
      secret: l31n4op3rtur8e4p1
    bloqueio-ligacao-api:
      client: bloqueio-ligacao-api
      secret: bl0qu310l1g4c404p1

  services:
    autenticacao:
      #url: http://localhost:8096
      url: https://autenticacao-api-dev.conexaoclarobrasil.com.br
    call:
      url: http://call-api-dev.conexaoclarobrasil.com.br
      # url: http://localhost:8094
    parceiros-online:
      url: https://parceiros-dev.conexaoclarobrasil.com.br/
      #url: http://localhost:8099
    vendas:
      #url: http://localhost:8097
      url: https://vendas-api-dev.conexaoclarobrasil.com.br/
    mailing:
      #url: http://localhost:8095
      url: https://mailing-api-dev.conexaoclarobrasil.com.br/
    equipe-venda:
      #url: http://localhost:8089
      url: https://api-dev.conexaoclarobrasil.com.br/equipe-venda
    contato-crn:
      #url: http://localhost:8084
      url: http://api-dev.conexaoclarobrasil.com.br/contato-crn
    comunicados:
      url: http://api-dev.conexaoclarobrasil.com.br/comunicados/
    claro-indico:
      #url: http://localhost:8055
      url: http://api-dev.conexaoclarobrasil.com.br/claro-indico/
    agente-autorizado:
      #url: http://localhost:8300
      url: https://api-dev.conexaoclarobrasil.com.br/parceiros/agente-autorizado
    gestao:
      #url: http://localhost:8091
      url: http://gestao-api-dev.conexaoclarobrasil.com.br
    solicitacao-pap:
      #url: http://localhost:8108
      url: https://api-dev.conexaoclarobrasil.com.br/solicitacao-cliente-pap
    consulta-cep:
      url: http://192.168.2.28:8186
    notificacao:
      #url: http://localhost:8081
      url: http://192.168.50.1:6595
    emails:
      #url: http://localhost:8080
      url: http://api-hom.conexaoclarobrasil.com.br/email
    integracao-vendas:
      #url: http://localhost:8086
      url: http://192.168.50.1:6545
    mailing-importacao:
#      url: http://localhost:8087
      url: http://192.168.50.1:6530
    lei-nao-perturbe:
      #url: http://localhost:8109
      url: http://192.168.50.1:8109
    extrato-comissao:
      #url: http://localhost:8309
      url: http://192.168.50.1:8309
    funil-prospeccao:
      #url: http://localhost:8100
      url: http://192.168.50.1:6605

flyway:
  enabled: true
  out-of-order: true
  baseline-on-migrate: true

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    call:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.call.url}
    vendas:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.vendas.url}
    parceiros:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.parceiros-online.url}
    mailing:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.mailing.url}
    equipe-venda:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.equipe-venda.url}
    contato-crn:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.contato-crn.url}
    comunicados:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.comunicados.url}
    claro-indico:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.claro-indico.url}
    solicitacao-pap:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.solicitacao-pap.url}
    gestao:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.gestao.url}
    agente-autorizado:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.agente-autorizado.url}
    emails:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.emails.url}
    integracao-vendas:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.integracao-vendas.url}
    mailing-importacao:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.mailing-importacao.url}
    lei-nao-perturbe:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.lei-nao-perturbe.url}
    extrato-comissao:
      sensitive-headers: Cookie,Set-Cookie
      url: ${app-config.services.extrato-comissao.url}
    funil-prospeccao:
      sensitiveHeaders: Cookie,Set-Cookie
      url: ${app-config.services.funil-prospeccao.url}

  host:
    connect-timeout-millis: 1800000
    socket-timeout-millis: 1800000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
  shareSecurityContext: true

feign:
  client:
    config:
      agenteAutorizadoNovoClient:
        connectTimeout: 360000
        readTimeout: 360000

management:
  metrics:
    export:
      simple:
        enabled: false

xbrain:
  logging:
    level: INFO
    appender: CONSOLE
    appName: ${spring.application.name}

keys:
  public: |
    -----BEGIN RSA PUBLIC KEY-----
    MIIBCgKCAQEAwO+B3hQoB69bFn8Tsy+VJAnQFxvgVGlMxRMkJIdqYn+DQwnzipdI
    SU1rR3lieZUSwGk1Z7IW2ePWilnSBBZlkEo10Nf3vhMr00NyntIxy2yYjGlpthiL
    8vG91vjC0xIinZJYhYyz2v5E0PYZU/WODu2pA3OeoKyUfj5uzpCzcH8VVQYTSbkx
    U5/oNenBSB1sNkVzuTKy17Bg9lxCppi2AT9azEXkqefrvDDneLpCvJ4He5cFHQGx
    M0QkWHhyxPjLHAYgBWCPJLwRtDuNZoPHbbMPthzMwshgKzrTu/It8YvfdYRk+WSw
    3OrTvTOoZZa6V4wTECWLj3TGocKISC2Z1QIDAQAB
    -----END RSA PUBLIC KEY-----
  private: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAwO+B3hQoB69bFn8Tsy+VJAnQFxvgVGlMxRMkJIdqYn+DQwnz
    ipdISU1rR3lieZUSwGk1Z7IW2ePWilnSBBZlkEo10Nf3vhMr00NyntIxy2yYjGlp
    thiL8vG91vjC0xIinZJYhYyz2v5E0PYZU/WODu2pA3OeoKyUfj5uzpCzcH8VVQYT
    SbkxU5/oNenBSB1sNkVzuTKy17Bg9lxCppi2AT9azEXkqefrvDDneLpCvJ4He5cF
    HQGxM0QkWHhyxPjLHAYgBWCPJLwRtDuNZoPHbbMPthzMwshgKzrTu/It8YvfdYRk
    +WSw3OrTvTOoZZa6V4wTECWLj3TGocKISC2Z1QIDAQABAoIBADHBUmd4IT6iHUZ2
    7Rinq7mIgk6DVN3P7glgv1BgT7IpGiu+tDzIeM7WlVTwW9Ho/NX8C9a7GaOFWz2A
    nmWJdRW53ZkHKQ+ul/26hiOpJ0hDsC99u9JHEEhNyVxX+L5ADgc+x29hcryGGC8f
    WDbLu5/j8FNAjOb4uq634RGKRYw79p279LoGf+f1HBwCTQmZ3HN8svQi1HoivMi6
    +aXDgDfnu0+pIvaiBZGkNKpkcGKiF2YC+FFB7Ly3AaF2C36O616MjFAsb0Bk1ge3
    FIapZsUn1qU0+2CSdez/5kRBjQWpi5moVGMvdR7MOYn8Nvwu9aVc+G2kYW8wmSFo
    Om2qmr0CgYEA9BTzsEMK4Lk2p3ch8/cjNa4Fl80Jv8+ZotjE3+pC/XCQVEtAWsoe
    aK0HRgyJBpb05Maw/2TNg1IiWoZXiiSkQHit3zrmlvwZm1zBi5pdHnpuW+tjEwnC
    WWywHpfI7vMQ2Ydc03JCbDwVGWKa1CleujdSLMZuSzbkNymRTd9wTccCgYEAyls4
    xw6wtYk78naspIbfQCFSteAqsnXXSv214taNV1SJG+5cfPzPIOGaj+sy2AoOOfSt
    VlA+/okGjHu/+8c01wR4ANwJIfeWUrUhB5pJv8S2Wn/b/o7AKSLg4AFHv3utZfG6
    9qwE7HQZt8aVe2RQVEclC5X4CLeoQrwLqn+vy4MCgYEA54fkbWP7MpaeoJaij4D0
    VlxAE/I8eEXeUBpeDqVybGTVlBBZ+IVX+SWBC9KiPKz/mvBbP7iINjS4P7TF31XI
    tRuEm4eM6tYzGCwRsHJ6OIocm3ca4RlV0WwHWM3Unc3WQvJjfHQbS/5maVEe23hu
    0ifd/HkycIieTTFSE1OLfUsCgYEAg1ZBu7DlMG4p4mz0ELUZIV5/eFxOWhXx7lJN
    QzVN92h+tQo4LUdIiGblEpPtJBsisKsF9gePW1VEUtne+WOKACR+XtBxfQJdJsE4
    9t5FD5p1YLer6cRtJEXm/nzWPInhOVFzr7ZmW7HfH1BcpQGuwYSLnsFvgvjw1J+I
    UtkdGFECgYEA4YfAR1eSBmkvaVTqViXmNd2UI5lmo3lm/VvT2AhwOSdg8FIh124Y
    rdHOkFQIId5u5VqWoq/USR2Ek3ecCvlO/74mApTTT2Foc6JftqL8eqd3DI+ZiI0g
    I19GBb8PGGkHbVCVrisVpld6hL3wqDrGTZ3sT2fM748v2LoMd9bZlPE=
    -----END RSA PRIVATE KEY-----
