server:
  tomcat:
    max-threads: 5000
    min-threads: 10

spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.2.38:1521/xprod
    username: AUTENTICACAO
    password: 4ut3nt1c4c40
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximumPoolSize: 30

  rabbitmq:
    host: 172.10.10.60
    port: 5672
    username: xbrain
    password: xbrain

app-config:
  # TODO: Quando permitido, alterar novamente para Conex√£o Claro Brasil
  url: https://parceirosonline.com.br
  url-estatico-upload: ${app-config.url-estatico}/producao/autenticacao
  upload-dir: ${app-config.estatico-dir}/producao/autenticacao

  services:
    call:
      url: http://172.10.10.78:8094
    parceiros-online:
      url: http://172.10.10.76:8099

  email:
    enviar: true
    emails:

logging:
  level:
      org.springframework: 'ERROR'
      org.hibernate: 'ERROR'